<?php

/**
 * @file
 * Contains unsplash_stream_test.module.
 */

/**
 * Implements hook_entity_presave().
 *
 * @param $entity
 */
function unsplash_stream_test_entity_presave($entity) {
  /**
   * Editor's note: This is an absolute hammer, intended only for testing purposes.
   * A field base is provided in the module, in order to test one must add an
   * instance of that field to an entity that also has an instance of field_image.
   */
  $type = $entity->getEntityTypeId();
  $types = ['node', 'media'];
  $unsplash_field = 'field_unsplash_image_id';
  $image_field = 'field_image';
  if (in_array($type, $types)
      && $entity->hasField($unsplash_field)
      && !$entity->get($unsplash_field)->isEmpty()
      && $entity->hasField($image_field)
  ) {
    $id = $entity->get($unsplash_field)->value;
    $raw_image = file_get_contents('unsplash://' . $id);
    $filename = $id . '.jpg';
    $file = file_save_data($raw_image, "public://$filename", FILE_EXISTS_REPLACE);
    $entity->$image_field->setValue(['target_id' => $file->id()]);
  }
}

